### ISSUE TITLE
[Epic] Actions

### ISSUE THREAD

**Issue by tsherrell** [tsherrell/Portfolio#1]
## User story:
As a user, when I am presented with a response from the product that calls for me to do something, I would like to be able to take action (with the product performing as much of each task as possible) from directly within the product so, I am not hindered by performing digital or physical cognitive switching.

![Actions Process Flow Overview](https://github.com/ApoktoAI/trent-product-backlog/assets/1414813/ca37ac69-d32b-4c3d-8bbe-48e8b9016b83)

[Link to diagram](https://excalidraw.com/#json=O52ud9SKeJ2hY38_RjR_f,gC-q816j4lXDlFBkjGcx1g)

## Description:
**Question --> Answer --> Action**

The basic concept of the 'Actions' epic is to build in functionality that takes the question and answer interaction to the next level by having the product perform subsequent tasks.

## Use cases:

1. User asks a question about a task that results in one or more steps required of the user to accomplish said task.
2. Required next steps can be performed via digital means, i.e., API, email, SMS, etc.

## Example scenarios (not exhaustive):

**1. Maternity benefits question:**
  a) A user asks the product a benefits question.
  b) the product returns the requested information along with the steps required to accomplish the beneficial goal.
  c) The user is prompted to allow the product to perform those next steps, i.e., scheduling appointments, suggesting and e-commerce of products and services, calendar management/alerts, etc.
  d) the product provides feedback at each step informing the successful accomplishment.

**2. Leave of absence question.**
  a) A user asks the product about their employer's policy regarding taking a leave of absence.
  b) the product returns the requested information along with the required steps.
  c) The user is prompted to allow the product to perform those next steps, i.e., generating a request email and scheduling sending it to the appropriate person(s) at the appropriate time, setting up reminders within the user's calendar, etc.
  d) the product provides feedback at each step informing the successful accomplishment.

## Additional links or resources:

[Figma prototype of example maternity flow.](https://www.figma.com/proto/o5fQoKzPsi1OiXme58n8Uo/EPHY?page-id=0%3A1&node-id=2073-2&viewport=-883%2C-2330%2C0.08&t=OdUfAoC26Er9hGiz-1&scaling=contain&content-scaling=fixed&starting-point-node-id=2073%3A2)
[Screen video of example maternity flow. (Same as prototype above.)](https://drive.google.com/file/d/1DCTWctQwrU3G14cSLU7R987ptDRnMngB/view?usp=sharing)

## Acceptance criteria:

- [ ] If the product returns followup action(s) that can be performed by the tool, it prompts the user suggesting allowing the product to take care of the step(s).
- [ ] If an action requires the user's input (like choosing the date/time of an appointment), the system generates a visually pleasing and understandable 'in-line widget' to facilitate the interaction.
- [ ] The system provides feedback when an action is successfully accomplished.
- [ ] The system provides feedback and steps to remedy when a action is not able to be successfully accomplished.
- [ ] The system asks the user yes/no (or other appropriate question) before performing any task on their behalf.
- [ ] The system is able to set actions to happen at a future date/time, i.e, a reminder or sending of an email.
- [ ] The system is capable of suggesting products and/or services related and appropriate to the original AI query.
- [ ] Ecommerce is able to be performed within the product at the point of sale.
- [ ] All interaction with the product is in-line and does not require the user to leave or navigate to another part of the product. 

## User story tickets:

- [ ] [[User story] Perform Actions?](https://github.com/tsherrell/work-examples/issues/2)
- [ ] [[User story] In-line Widget](https://github.com/tsherrell/work-examples/issues/3)
- [ ] [[User story] Confirmation](https://github.com/tsherrell/work-examples/issues/4)
- [ ] [[User story] Error](https://github.com/tsherrell/work-examples/issues/5)
- [ ] [[User story] Sub-action permission](https://github.com/tsherrell/work-examples/issues/6)
- [ ] [[User story] Future time/date](https://github.com/tsherrell/work-examples/issues/7)
- [ ] [[User story] Marketing of additional products and/or services](https://github.com/tsherrell/work-examples/issues/8)
- [ ] [[User story] Ecommerce](https://github.com/tsherrell/work-examples/issues/9)
